# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem "mysql2"
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &mysql_default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: localhost

development:
  <<: *mysql_default
  database: ai_quiz_maker_api_development

test:
  <<: *mysql_default
  database: ai_quiz_maker_api_test

# PostgreSQL configuration for production
# Install the PostgreSQL driver
#   gem install pg
#
# Ensure the PostgreSQL gem is defined in your Gemfile
#   gem "pg"

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ai_quiz_maker_api
  password: <%= ENV["AI_QUIZ_MAKER_API_DATABASE_PASSWORD"] %>
  host: localhost # or your production database host
  database: ai_quiz_maker_api_production
  port: 5432 # default PostgreSQL port, adjust if necessary
